// paths
const PROFILE_IMAGE = "profile_images/"
const FAVOR_IMAGE = "/favor_images/"
const STATIC_FILE_PATHS = "./data"
const PROFILE_IMAGES_PATH = STATIC_FILE_PATHS + PROFILE_IMAGE
const FAVOR_IMAGES_PATH = STATIC_FILE_PATHS + FAVOR_IMAGE


module.exports = {PROFILE_IMAGE, STATIC_FILE_PATHS, PROFILE_IMAGES_PATH, FAVOR_IMAGES_PATH, FAVOR_IMAGE}